### PR TITLE
Added Toggle button to NavBar

### LINKED ISSUE #14: Make the navbar responsive in smaller screen size
In smaller screen sizes the icons are stacked on the navbar and looks clumsy.
 
nav

Make the navbar responsive in smaller screen size by adding a toggle button and on click of the toggle button and menu should open with the options present on the navbar currently. Those options on the menu should navigate to the respective pages properly.

For reference please refer the link given below:
[Responsive Nav](https://codepen.io/janheise/details/JjdwXyz)

### PR DESCRIPTION
**Pull request by Patil-Mandar**
Added toggle button which will be visible only on small screen. Clicking it will show Icons to go to other pages. 
image
image
Fixes #14

### CODE REVIEW

**Review by AbhipsaGuru1012 — CHANGES_REQUESTED** [review]
@Patil-Mandar the changes that you have made works fine for smaller screen size but in larger screen size the sidenav is getting distorted because of the changes that you have added. 

I am attaching the image of the screen below -
changes

Please add the necessary changes.

**Comment by AbhipsaGuru1012** [comment]
@Patil-Mandar can you please update about the progress?

**Comment by Patil-Mandar** [comment]
Hey @AbhipsaGuru1012 I am not feeling well from few days, that's why I won't able to code. You can assign this issue to others.
Sorry for inconvenience.

**Comment by AbhipsaGuru1012** [comment]
> Hey @AbhipsaGuru1012 I am not feeling well from few days, that's why I won't able to code. You can assign this issue to others. Sorry for inconvenience.

Okay, no worries

**Pull request closed without merging**
